//! The command-line interface.
//!
//! Ported from `cmd.ts`. Commander becomes clap; every command, argument and
//! flag keeps its original name so existing scripts and container commands
//! continue to work.

use clap::{Parser, Subcommand};

use crate::constants::{PROGRAM_NAME, PROGRAM_VERSION};

#[derive(Debug, Parser)]
#[command(
    name = PROGRAM_NAME,
    version = PROGRAM_VERSION,
    about = "Fully-automatic cross-seeding with Torznab",
    disable_version_flag = true
)]
pub struct Cli {
    /// Output the current version.
    #[arg(short = 'V', long = "version", action = clap::ArgAction::Version)]
    pub version: Option<bool>,

    #[command(subcommand)]
    pub command: Command,
}

#[derive(Debug, Subcommand)]
pub enum Command {
    /// Start the crust-seed daemon
    Daemon {
        /// Listen on a custom port
        #[arg(short = 'p', long)]
        port: Option<u16>,
        /// Bind to a specific IP address
        #[arg(long)]
        host: Option<String>,
        /// Serve crust-seed behind this base path
        #[arg(long = "base-path", default_value = "")]
        base_path: String,
        /// Do not listen on any port
        #[arg(long = "no-port")]
        no_port: bool,
        #[arg(short = 'v', long)]
        verbose: bool,
    },

    /// Search for cross-seeds
    Search {
        /// torrent files separated by spaces
        #[arg(long, num_args = 1.., hide = true)]
        torrents: Vec<String>,
        #[arg(short = 'v', long)]
        verbose: bool,
    },

    /// Run an rss scan
    Rss {
        #[arg(short = 'v', long)]
        verbose: bool,
    },

    /// Inject saved cross-seeds into your client (without filtering, see docs)
    Inject {
        /// Directory of torrent files to try to inject
        #[arg(long = "inject-dir")]
        inject_dir: Option<String>,
        /// Searchee and candidate titles do not need to pass the fuzzy matching check
        #[arg(long = "ignore-titles", overrides_with = "no_ignore_titles")]
        ignore_titles: bool,
        /// Searchee and candidate titles need to pass the fuzzy matching check (default)
        #[arg(long = "no-ignore-titles", overrides_with = "ignore_titles")]
        no_ignore_titles: bool,
        #[arg(short = 'v', long)]
        verbose: bool,
    },

    /// Use snatched torrents from torrent_cache to attempt to restore cross seeds.
    /// Will need to run `crust-seed inject` afterwards with dataDirs configured.
    Restore {
        #[arg(short = 'v', long)]
        verbose: bool,
    },

    /// Analyze two torrent files for cross-seed compatibility
    Diff { searchee: String, candidate: String },

    /// Print a torrent's file tree
    Tree { torrent: String },

    /// Update announce urls in the torrent cache
    #[command(name = "update-torrent-cache-trackers")]
    UpdateTorrentCacheTrackers {
        /// A substring of the announce url to replace
        old_announce_url: String,
        /// The replacement substring
        new_announce_url: String,
    },

    /// Clear the cached details of indexers (failures and caps)
    #[command(name = "clear-indexer-failures")]
    ClearIndexerFailures,

    /// Clear the cache without causing torrents to be re-snatched, and reset the
    /// timestamps for excludeOlder and excludeRecentSearch
    #[command(name = "clear-cache")]
    ClearCache,

    /// Clear crust-seed's cache of your client's torrents
    #[command(name = "clear-client-cache")]
    ClearClientCache,

    /// Show the api key
    #[command(name = "api-key")]
    ApiKey {
        /// Provide your own API key to override the autogenerated one
        #[arg(long = "api-key")]
        api_key: Option<String>,
    },

    /// Reset the api key
    #[command(name = "reset-api-key")]
    ResetApiKey,

    /// Delete all users and sessions
    #[command(name = "reset-user")]
    ResetUser,

    /// Create a development login URL
    #[command(name = "dev-login")]
    DevLogin {
        /// Use a specific username
        #[arg(long)]
        user: Option<String>,
        /// Origin where crust-seed is running
        #[arg(long, default_value = "http://localhost:2468")]
        origin: String,
        /// Local path to open after login
        #[arg(long = "redirect-to", default_value = "/settings/general")]
        redirect_to: String,
    },

    /// Send a test notification
    #[command(name = "test-notification")]
    TestNotification {
        #[arg(short = 'v', long)]
        verbose: bool,
    },
}

impl Command {
    /// Whether `--verbose` was passed, which raises the console log level.
    pub fn verbose(&self) -> bool {
        match self {
            Command::Daemon { verbose, .. }
            | Command::Search { verbose, .. }
            | Command::Rss { verbose }
            | Command::Inject { verbose, .. }
            | Command::Restore { verbose }
            | Command::TestNotification { verbose } => *verbose,
            _ => false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::CommandFactory;

    #[test]
    fn the_cli_definition_is_valid() {
        Cli::command().debug_assert();
    }

    /// Every command cross-seed exposed must still exist under the same name.
    #[test]
    fn every_original_command_is_present() {
        let command = Cli::command();
        let names: Vec<String> = command
            .get_subcommands()
            .map(|c| c.get_name().to_string())
            .collect();
        for expected in [
            "daemon",
            "search",
            "rss",
            "inject",
            "restore",
            "diff",
            "tree",
            "update-torrent-cache-trackers",
            "clear-indexer-failures",
            "clear-cache",
            "clear-client-cache",
            "api-key",
            "reset-api-key",
            "reset-user",
            "dev-login",
            "test-notification",
        ] {
            assert!(names.iter().any(|n| n == expected), "missing {expected}");
        }
    }

    #[test]
    fn daemon_flags_parse() {
        let cli = Cli::try_parse_from([
            "crust-seed",
            "daemon",
            "-p",
            "9000",
            "--host",
            "127.0.0.1",
            "--base-path",
            "/cs",
            "-v",
        ])
        .unwrap();
        match cli.command {
            Command::Daemon {
                port,
                host,
                base_path,
                verbose,
                no_port,
            } => {
                assert_eq!(port, Some(9000));
                assert_eq!(host.as_deref(), Some("127.0.0.1"));
                assert_eq!(base_path, "/cs");
                assert!(verbose);
                assert!(!no_port);
            }
            other => panic!("unexpected {other:?}"),
        }
    }

    #[test]
    fn no_port_is_recognised() {
        let cli = Cli::try_parse_from(["crust-seed", "daemon", "--no-port"]).unwrap();
        assert!(matches!(cli.command, Command::Daemon { no_port: true, .. }));
    }

    /// `--no-ignore-titles` must be able to cancel `--ignore-titles`, as
    /// Commander's negatable option did.
    #[test]
    fn ignore_titles_can_be_negated() {
        let cli = Cli::try_parse_from([
            "crust-seed",
            "inject",
            "--ignore-titles",
            "--no-ignore-titles",
        ])
        .unwrap();
        match cli.command {
            Command::Inject {
                ignore_titles,
                no_ignore_titles,
                ..
            } => {
                assert!(!ignore_titles);
                assert!(no_ignore_titles);
            }
            other => panic!("unexpected {other:?}"),
        }
    }

    #[test]
    fn diff_takes_two_positional_torrents() {
        let cli = Cli::try_parse_from(["crust-seed", "diff", "a.torrent", "b.torrent"]).unwrap();
        match cli.command {
            Command::Diff {
                searchee,
                candidate,
            } => {
                assert_eq!(searchee, "a.torrent");
                assert_eq!(candidate, "b.torrent");
            }
            other => panic!("unexpected {other:?}"),
        }
    }

    #[test]
    fn the_search_torrents_flag_takes_many_values() {
        let cli =
            Cli::try_parse_from(["crust-seed", "search", "--torrents", "a", "b", "c"]).unwrap();
        match cli.command {
            Command::Search { torrents, .. } => assert_eq!(torrents, vec!["a", "b", "c"]),
            other => panic!("unexpected {other:?}"),
        }
    }

    #[test]
    fn verbose_is_reported_per_command() {
        let cli = Cli::try_parse_from(["crust-seed", "rss", "-v"]).unwrap();
        assert!(cli.command.verbose());
        let cli = Cli::try_parse_from(["crust-seed", "clear-cache"]).unwrap();
        assert!(!cli.command.verbose());
    }
}
